### ISSUE TITLE
Possibly support "Mouse follows focus"?

### ISSUE THREAD

**Issue by nogweii** [kwin-scripts/kwin-tiling#1]
One of the awesome things I liked when using tilling window managers is focus follows mouse, which is easy enough to do in KDE. (Systemsettings -> Window Behaviour)

However, if I switch a windows' focus via a shortcut key (Alt+Tab, for instance), I'd like the mouse to jump to the center of the newly focused window.

Or would this be more appropriate as a separate script?

**Comment by setzer22** [comment]
For anyone interested, I created this python script that implements mouse-follows-focus using Xlib: https://github.com/setzer22/mouse-follows-focus/blob/master/mouse-follows-focus.py

The script works well with focus-follows-mouse, because the mouse won't be warped if it's already inside the currently focused window, so it will only move when using the keyboard to change focus. I'm using this with kwin-tiling and works flawlessly!
