### ISSUE TITLE
TilingManager._currentScreen is never updated

### ISSUE THREAD

**Issue by setzer22** [kwin-scripts/kwin-tiling#106]
The title pretty much describes the issue. The field `_currentScreen` is declared inside TilingManager, but I don't see it getting updated anywhere (unlike `_currentDesktop` for which changes are tracked in a signal handler). 

I see no reason to keep this property when we can query `workspace.activeScreen` any time this is needed. And of course, this causes issues with multi-monitor setups (e.g. moveTile does not work on any monitor but the first one).

Since we're at it, even though `_currentDesktop` is correctly handled, I don't see why we shouldn't query `workspace.currentDesktop` directly as well.

**Comment by faho** [comment]
>Since we're at it, even though _currentDesktop is kept track of, if it's a global property I don't see any need for not querying workspace.currentDesktop.

The reason it's being tracked is so we can deactivate the _old_ desktop when the current desktop changes. Think of it as a "last desktop", since I don't think that kwin's "currentDesktopChanged" signal sends that.

currentScreen was added purely for symmetry - "surely we need that as well?" - but since I don't think a "currentScreenChanged" would be of interest to us, we can probably remove it.

**Comment by setzer22** [comment]
You're right, I did not see that. Thanks for the input!

I don't think the _currentScreen is needed because all screens are visible at the same time. Moreover, I did not see a "screenChanged" event in kwin's script API that we could hook onto. 

I went ahead and replaced _currentScreen with workspace.activeScreen in one of my branches. Everything seems to work fine, and now moveTile works in all screens.
