### ISSUE TITLE
conky is always on top

### ISSUE THREAD

**Issue by tflori** [kwin-scripts/kwin-tiling#138]
I have a problem with conky. Bevor using kwin-tiling I used to have conky as a normal window with window hint "below". But with kwin-tiling all windows go below and therefor conky is on top of all windows.

I tried to switch to to override window but then I have a black background. I read a lot of recommendations to use feh or qiv to set the root background but it seems not to work at all.

But I'm wondering why we need to set all windows below that are tiled? Can we add an option not to do so? Should floating windows not be above? and tiles are "normal"?

**Comment by faho** [comment]
>But I'm wondering why we need to set all windows below that are tiled?

Because tiled windows take up the entire screen, so if you're to have floating windows at all, and they need to be visible, they'll have to be above the tiled windows.

Which means either the tiled windows need to be set keepBelow, or the floating windows need to be set keepAbove.

I'm afraid I don't see a solution to this.

**Comment by tflori** [comment]
but why we need to set it? by default a window is above another window when it has focus. a floating window that does not have focus is below the tiling windows. in my opinion this is just forcing users to close all floating windows before continuing to work

**Comment by faho** [comment]
If floating windows weren't above tiling windows, they could entirely disappear behind them, and you couldn't move the tiling window to the side to get to it.

Sorry, this isn't happening.

**Comment by laloch** [comment]
@tflori: You missed the point - the tiling layout covers the whole screen and the X clients placed below the tiled windows would be never visible anyway. What would be the point of maintaining such a always-invisible layer?
Possible solution: you might want to embed your Conky in a Plasma widget...

**Comment by tflori** [comment]
ok, maybe it's somehow naive to think that people using plasma+kwin+kwin-tiling also having a task bar always visible. but i know these people exist (me) and I considered moving to i3 but at the end: they don't have a task bar and are less "fancy" that's the reason I kept at plasma but anyway the tiling script is awesome and I can have tiling in plasma, thx for that!

An option to disable the "keepBelow" lines in Tile.js is not that complicated to realize I guess. I already found ot that resizing with mouse is not possible anymore but I have to admit: who wan't to use a mouse when there is a shortcut for it? I just think it should be a decision of the user not the developer.

**Comment by tflori** [comment]
sorry false alarm. it's just firefox and konsole that both remove the borders (so I just don't have something to grep the edge for resizing). everything works as expected. a second option to "keepAbove" windows in floating mode would also be possible I guess.

**Comment by laloch** [comment]
> ok, maybe it's somehow naive to think that people using plasma+kwin+kwin-tiling also having a task bar always visible

I, for instance, do have a task bar always visible. How does it relate to Conky?

**Comment by tflori** [comment]
when you have a taskbar: where is the problem when a window is behind another window?

**Comment by faho** [comment]
The problem is that you need to use the taskbar to get the thing, which disappears seemingly randomly. KWin's stacking order here isn't good enough to rely on, because, unlike a full tiling WM, it doesn't have a special "tiling" layer.

If you really want this feature you'll have to patch it in yourself, in your own fork. The script is free software, so you're free to do that.

However, I now consider this matter closed and will not accept any more comments regarding it.
