### ISSUE TITLE
Make "Move Window" move across screen borders

### ISSUE THREAD

**Issue by stloewen** [kwin-scripts/kwin-tiling#156]
First of all: Thanks for sharing this awesome script.

Currently the "Move Window Up/Down/Right/Left" only move a window inside one screen but not across screen borders.

It would be cool if crossing screen borders would work.

**Comment by stloewen** [comment]
My very crude solution: fc4dcb39171808fbad7a7b9464629b5ee7240338

This is ugly and targeted at my setup, but maybe it can act as a starting point.

**Comment by laloch** [comment]
Hi @stloewen, thanks for sharing the patch.
KWin already handles moving windows between screens. Why do you think this is better?
@faho, what do you think?

**Comment by stloewen** [comment]
Multiple reasons:

1. KWin only has "Move to Next/Prev Screen" which is based on screen numbers and not on screen geometry (does not correspond to Left/Right/Up/Down)
2. Even if KWin provided the function it would be two different keybindings for the same action (i.e. move windows to the left)
3. KWin's functionality seemed buggy when I tested it. Although that is something to report to KWin and no reason to duplicate functionality.

**Comment by laloch** [comment]
For me 1. is a good reason by itself.

There's a comment in your patch:
>This is not completely trivial since clientArea reports screen areas
without panel areas. I know of no way to get the full screen geometry.
Therefore I do a search for the screen with minimal distance in given direction.

This is actually the correct way, because there's is no guarantee and nothing mandates the screens to be adjacent - there may be a gap between them and they may overlap.

I like the idea and the patch overall. Could you please replace the `if else if` construct with `switch` statement, implement the Up/Down directions and open a PR?

**Comment by faho** [comment]
>@faho, what do you think?

I have never really used multiple monitors in anger. Are there any cases where you'd move wrong? How bad does that feel? How much does that set you back?

I suppose not, since tiles have a rather predictable shape (a rectangle), so it's never really unclear if another tile on the same monitor is e.g. "left" of the current one or if it's on the edge. And if you moved wrong, you could presumably move back, though it might not result in the exact same layout as before.

So: Sure, why not.

**Comment by stloewen** [comment]
Well the predictability depends on the complexity of the monitor layout and also their tiling layouts.
We're currently discussing that in #157.

But for simple layouts it works great and even "unexpected" placements don't really feel like a set back to me and are quickly corrected.

**Comment by faho** [comment]
>Well the predictability depends on the complexity of the monitor layout and also their tiling layouts.

I feel like the most important prediction is "does this move to another monitor or not". Good placement if it does is a cherry on top, but as long as you're not mislead about that question it's alright.

**Comment by stloewen** [comment]
In that case predictability is really high. I haven't found a scenario where it did not switch screens although I expected it to.

**Comment by laloch** [comment]
Closed by #157.
