### ISSUE TITLE
HalfLayout: Multi-Master split direction unintuitive

### ISSUE THREAD

**Issue by stloewen** [kwin-scripts/kwin-tiling#169]
When using HalfLayout in the default rotation new tiles usually open as horizontal splits.
However, increasing the master count leads to the left half being split vertically.
I find this to be really unintuitive. Wouldn't it make more sense to arrange multiple masters in horizontal splits?

**Comment by faho** [comment]
This is because your monitor is wider than it is high, so there's more space to be divided vertically.

But when it comes to layouts, there are 535890580934 possibilities, and we really don't want to offer them all.

For this specific case, I'd think that a gridlayout, that divides the screen a bit more evenly, would work fine, so I'm closing this in favor of #168.

**Comment by stloewen** [comment]
GridLayout sounds like a great alternative to my proposal. Thanks!
