### ISSUE TITLE
Manual tiling a la i3

### ISSUE THREAD

**Issue by DavidGamba** [kwin-scripts/kwin-tiling#19]
I like this plugin but the concept of pre-made layouts (one master on the side and splits on the other) is something I find lacking in flexibility. Is there a way to have a layout that allows me to split vertically or horizontally any section at will?

**Comment by DaBlitzStein** [comment]
Free layouts are needed to be a MAJOR thing.
I wish this behaviour like i3wm. Things like move windows between monitors in a simple way is a good enhancement.

**Comment by setzer22** [comment]
I want to start working on this. Is there any general advice you could give me, @faho?

 My idea was to create a new layout class and work from there. Manual tiling would be a new kind of layout in which  you can manually define the partitions. There will be some tree-like structure to store the current layout, and new windows should be placed relative to the currently focused window. Do you see any drawbacks in this approach?

**Comment by setzer22** [comment]
I'm having a closer look at the source. The documentation and diagrams really helped. However, right now I am not sure on how to set up a proper development environment: What's a good way to iteratively develop/debug this script? I see there's several console.log and print statements scattered accross, where do these get written when the script is running?

I see there's a "Desktop Console" application which lets me test short JS snippets on the fly. However, I did not find a proper way of running this plugin on it, since the main entry point is a qml file and I don't think this shell supports running multi-file projects.

Any directions will be much appreciated!
