### ISSUE TITLE
Add monocle layout

### ISSUE THREAD

**Issue by matejdro** [kwin-scripts/kwin-tiling#209]
Simple layout where all windows on the screen are maximized and then you can use focus next/previous tile shortcuts, alt tab or any other means that KWin already provides to switch between windows

Preferably there would be a shortcut to toggle between regular tiling and monocle.

**Comment by laloch** [comment]
Hi @matejdro, I believe that the functionality, you are asking for, is already implemented (provided, that your Plasma version is >= 5.16). Just maximize one of the tiled windows.

**Comment by matejdro** [comment]
Wow, you are correct. Thanks!

Any chance you can add that to the README.MD? I cannot find this. It is pretty neat hidden features.

Also I've noticed it is a bit glitchy (when alt tabbing, it kept resizing windows between normal to maximized until alt tab menu is gone). Should I create new issue for that?

**Comment by laloch** [comment]
> Any chance you can add that to the README.MD? I cannot find this. It is pretty neat hidden features.

Yes, we should probably mention that in the README.

> Also I've noticed it is a bit glitchy (when alt tabbing, it kept resizing windows between normal to maximized until alt tab menu is gone). Should I create new issue for that?

Yes, I'm aware of that. Plasma task switcher simply shows windows in their current state if the "Show selected window" option is enabled. To prevent it, we would have to maximize all windows in the current layout, which would lead to unnecessary layout recalculation and repaint of all windows on the respective screen. I'm afraid that if you'd open an issue against this behavior, we would close it as a won't-fix because of the implied recalculation overhead.

**Comment by matejdro** [comment]
To be honest, "Show selected window" is not that important to me, I prefer having glitchless tiling. (If you add maximizing feature to README it might also be worth to mention that "show selected writing" should be off.

Great script, by the way.

**Comment by matejdro** [comment]
Reopening. While this functionality is present, it is not really a layout and only treated as temporary state as explained in https://github.com/kwin-scripts/kwin-tiling/issues/216#issuecomment-663814643 .

**Comment by faho** [comment]
Calling this a special case of #126 - a layout restricted to N windows, and here N is 1.
