### ISSUE TITLE
Behaviour of maximized and tiled window

### ISSUE THREAD

**Issue by piotr-dobrogost** [kwin-scripts/kwin-tiling#73]
Currently when a tiled window is maximized and one tries to activate some other window (by clicking on the task manger or using keyboard (<kbd>Alt</kbd>+<kbd>Tab</kbd>)) the maximized window behaves as if it were set to _Keep Above Others_ and prevents any other window to be shown/activated. This is very confusing. I think in such a scenario the maximized window could
1. be unmaximized
2. left maximized but do not act like set to _Keep Above Others_ and all others windows should be shown *above* the maximized one

I think 1. is more in line with tiling paradigm and the fact that maximized window is still tiled as it was not set as floating. In other words we should think of maximizing tiled window as a temporary operation.

**Comment by faho** [comment]
>be unmaximized

We actually can't _really_ do that, because kwin doesn't expose the maximized state as a property. We only get a signal if it changed but we cannot change it ourselves. That means we could of course just tile the window, but if you have titlebars visible it would still show the window as maximized, and if you clicked the button we would receive the signal that it has been unmaximized.

>left maximized but do not act like set to Keep Above Others and all others windows should be shown above the maximized one

It's not actually set "Keep Above Others", it's just not set "Keep Below Others" (`client.keepBelow = false`). Because that's what tiled windows are set to, to allow floating windows to stay above them. Removing that would also lead to weird z-fighting issues. It would go below some but above other windows (because kwin seems to keep some stacking order).

**Comment by piotr-dobrogost** [comment]
> We actually can't really do that, because kwin doesn't expose the maximized state as a property.
Are there any technical reasons this can't be exposed? Is there any bug for this? Are there any other means to programmatically unmaximize window?

**Comment by faho** [comment]
There's no bug or technical reason I'm aware of. Personally, I'm not even really sure what maximizing a window in a tiling framework should mean.

The definition I've been going by is that it should allow you to temporarily focus on one particular window.

**Comment by piotr-dobrogost** [comment]
> The definition I've been going by is that it should allow you to temporarily focus on one particular window.

Agree.

> That means we could of course just tile the window, but if you have titlebars visible it would still show the window as maximized, and if you clicked the button we would receive the signal that it has been unmaximized.

Sure. In this case I think it should be tiled back to where it was before maximizing so that all tiled windows would be visible again. This would be much better than what we have currently.

**Comment by piotr-dobrogost** [comment]
> In this case (when someone tries to activate some tiled window, different than the maximized one) the maximized one should be tiled back to where it was before maximizing so that all tiled windows would be visible again. This would be much better than what we have currently.

@faho 
Do you agree with above?

**Comment by faho** [comment]
> Do you agree with above?

I don't think so. The issue is this:

>In this case (when someone tries to activate some tiled window, different than the maximized one) the maximized one should be tiled back

The problem here is that, especially with focus-follows-mouse, activating another window is really easy to do, and would cause the maximized window to snap back to its tiled position. Maybe it'll work if it's limited to tiled windows (because it'd be most annoying if it happened when you activate the panel or some floating dialog).

This might need some trials.

**Comment by piotr-dobrogost** [comment]
> Maybe it'll work if it's limited to tiled windows (...)

This should work.
Could you give me some precise directions which parts of source code should need to be changed to implement this?

**Comment by faho** [comment]
>Could you give me some precise directions which parts of source code should need to be changed to implement this?

The signals are connected in tilelist.js. You'll need to add "workspace.clientActivated" again. Maximization is currently only handled by tile (in tile.js), this'll need to be handed up to tiling.js (yes, the naming's kinda bad - it's essentially a "desktop", that consists of tiles and has a layout and stuff), so we can figure out if a tile on the current desktop is maximized.

There is some description in doc/design.txt, though as I look at it now it has a bunch of stuff about minutia, and a bit too little on the big-picture.

**Comment by nostalgicamigo** [comment]
In tilling WM, Alt+Tab does not serve any purpose. However in a maximized application, ALT+TAB should switch between neighbour windows, maximizing them instead.

What happens right now when an application is maximized is that ALT+TAB does not bring the neighbour window up. This is not the expected behaviour.

If it is feasible I would love this inclusion. Too many times I have to repeat "unmaximize" focus, "maximize", when I could simply ALT+TAB.

**Comment by faho** [comment]
>If it is feasible I would love this inclusion.

As you explained it, it's not. We cannot distinguish between alt+tab and other kinds of activation (we could override alt+tab with our own function, but that's not feasible either). That would mean that once you maximize a window, you'd always have one maximized one, and that seems really annoying, especially considering kwin currently sometimes maximizes windows without a reason that I can see.

What we might be able to do is make maximized windows unmaximize once you select a different tiled window. That would remove the "unmaximize" step from your desired workflow.

**Comment by lukrop** [comment]
The only really annoying thing I recognized is, that you'll experience the behaviour mentioned in the OP as long as the KWin script is loaded, even if the current desktop doesn't have tiling enabled. Disabled by default or disabled by shortcut.

**Comment by wd5gnr** [comment]
Is it just me or did the maximize behavior change recently? Seems like when I first started using the script, if I maximized a window it would take over my entire monitor (I no longer have multiples, just one 43"). Then restoring it would put it back in tiling. Now the window only maximizes to where it is tiled to. Did I break something or did something change in KWIN?
